### ISSUE TITLE
Crashes on eth_estimateGas

### ISSUE THREAD

**Issue by gagarin55** [ETCDEVTeam/sputnikvm-dev#47]
Following code with web3.js causes sputnikvm-dev panic:
```
const callData = {
    from: "0x0000000000000000000000000000000000000000",
    gasPrice: "0x04a817c800",
    gas: "0x5208",
    to: "0x0000000000000000000000000000000000000000",
    value: "0x0de0b6b3a7640000",
    data: "",
  }
  let gas = web3.eth.estimateGas(callData);
```

Result:
```
thread 'http.worker0' panicked at 'arithmetic operation overflow', /home/bill/.cargo/registry/src/github.com-1ecc6299db9ec823/etcommon-bigint-0.2.9/src/uint/mod.rs:1184:0
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /checkout/src/libcore/result.rs:906:4
```

sputnikvm-dev built by cargo run from master branch.

**Comment by sorpaas** [comment]
Turns out this require some refactoring of `sputnikvm-stateful`, but I'll get it done soon. In the mean time, setting `gasPrice` and `value` to zero would fix the issue.

**Comment by gagarin55** [comment]
Still doesn't work
